version: "3.9"
name: media
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - WEBUI_PORT=8080
    volumes:
      - /home/vlad/docker/configs/qbittorrent:/config
      - /mnt/storage/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    ports:
      - 7878:7878
    volumes:
      - /home/vlad/docker/configs/radarr:/config
      - /mnt/storage/downloads:/downloads
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /home/vlad/docker/configs/sonarr:/config
      - /mnt/storage/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - AUTO_UPDATE=true #optional
      # - RUN_OPTS=<run options here> #optional
    volumes:
      - /home/vlad/docker/configs/jackett:/config
      #- jackett-blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /home/vlad/docker/configs/jellyfin:/config
      - /mnt/storage/downloads/movies:/movies
      - /mnt/storage/downloads/shows:/shows
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Bucharest
    ports:
      - 5055:5055
    volumes:
      - /home/vlad/docker/configs/jellyseerr:/app/config
    restart: unless-stopped
