version: "3.9"
name: media
services:
  qbittorrent:
    image: qbittorrentofficial/qbittorrent-nox:latest
    container_name: qbittorrent
    environment:
      - PUID=$UID
      - PGID=$GID
      - TZ=$TIMEZONE
      - QBT_EULA=accept
      - QBT_VERSION=latest
      - QBT_WEBUI_PORT=8080
      - QBT_CONFIG_PATH=/config
      - QBT_DOWNLOADS_PATH=/downloads
    volumes:
      - $CONFIG/qbittorrent:/config
      - $DATA:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:develop
    environment:
      - PUID=$UID
      - PGID=$GID
      - TZ=$TIMEZONE
    ports:
      - 7878:7878
    volumes:
      - $CONFIG/radarr:/config
      - $DATA:/downloads
      - $MEDIA:/media
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr
    environment:
      - PUID=$UID
      - PGID=$GID
      - TZ=$TIMEZONE
    volumes:
      - $CONFIG/sonarr:/config
      - $DATA:/downloads
      - $MEDIA:/media
    ports:
      - 8989:8989
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=$UID
      - PGID=$GID
      - TZ=$TIMEZONE
    volumes:
      - $CONFIG/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:edge
    container_name: recyclarr
    user: $UID:$GID
    volumes:
      - $CONFIG/recyclarr/:/config
    environment:
      - TZ=$TIMEZONE

  jellyfin:
    image: jellyfin/jellyfin:unstable
    container_name: jellyfin
    environment:
      - PUID=$UID
      - PGID=$GID
      - TZ=$TIMEZONE
    volumes:
      - $CONFIG/jellyfin:/config
      - $CONFIG/jellyfin-cache:/cache
      - $MEDIA:/media
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=$TIMEZONE
    ports:
      - 5055:5055
    volumes:
      - $CONFIG/jellyseerr:/app/config
    restart: unless-stopped
