version: "3.9"
name: media
services:
  qbittorrent:
    image: qbittorrentofficial/qbittorrent-nox:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - QBT_EULA=accept
      - QBT_VERSION=latest
      - QBT_WEBUI_PORT=8080
      - QBT_CONFIG_PATH=/config
      - QBT_DOWNLOADS_PATH=/downloads
    volumes:
      - /home/vlad/docker/configs/qbittorrent:/config
      - /mnt/storage/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:develop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    ports:
      - 7878:7878
    volumes:
      - /home/vlad/docker/configs/radarr:/config
      - /mnt/storage/downloads:/downloads
      - /mnt/storage/media:/media
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:develop
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /home/vlad/docker/configs/sonarr:/config
      - /mnt/storage/downloads:/downloads
      - /mnt/storage/media:/media
    ports:
      - 8989:8989
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /home/vlad/docker/configs/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:edge
    container_name: recyclarr
    user: 1000:1000
    volumes:
      - /home/vlad/docker/configs/recyclarr/:/config
    environment:
      - TZ=Europe/Bucharest

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    volumes:
      - /home/vlad/docker/configs/jellyfin:/config
      - /home/vlad/docker/configs/jellyfin-cache:/cache
      - /mnt/storage/media:/media
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Bucharest
    ports:
      - 5055:5055
    volumes:
      - /home/vlad/docker/configs/jellyseerr:/app/config
    restart: unless-stopped
